### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by EngelschallNikolaus** [rstropek-teaching/pokelist-quiz-4ahif-EngelschallNikolaus#1]
Dear Mr. Stropek,

due to a lack of time because of some very demanding tests and also some bluescreens on my laptop this week, I wasn't able to finish the exercise in time. So by now, my solution is only able to go through all the pokemons with the previous and next buttons. (The details function is not working yet) I will try to finish the exercise today and check it in, if I'm able to do so.

Greetings, Nikolaus Engelschall

**Comment by rstropek** [comment]
@EngelschallNikolaus Thank you for letting me know. You don't need to rush. In our lesson today, we will discuss approaches to enhance the Pokemon example and your homework until next week will be to further improve your code -> you have another week to complete and perfect the Pokemon example.

Greetings,
Rainer Stropek.
