### ISSUE TITLE
homework link

### ISSUE THREAD

**Issue by EngelschallNikolaus** [rstropek-teaching/pokelist-quiz-4ahif-EngelschallNikolaus#2]
Here's my online solution link:
https://rawgit.com/rstropek-teaching/pokelist-quiz-4ahif-EngelschallNikolaus/master/index.html

Greetings, Nikolaus Engelschall

**Comment by rstropek** [comment]
@EngelschallNikolaus Thank you for your homework. I tried your program and it worked well 👍 .

One tip that came to my mind when looking at your code: You load *Bootstrap* from a CDN. Why not also loading *jQuery* from CDN (e.g. [Google CDN](https://developers.google.com/speed/libraries/#jquery))?

Greetings,
Rainer Stropek.
